name: Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Run Karoo GP tests
        run: pytest -v
